### ISSUE TITLE
d-env graph creation 

### ISSUE THREAD

**Issue by ghost** [mcapino/adpp-journal#1]
Hi,
do you have a tool to generate the graph in d-envs folder? For example, to generate a less dense graph or a graph for a new environment

**Comment by mcapino** [comment]
Hi, 
yes. There is a tool that generates a graph discretization for a given polygonal environment called "TriangulationGenerator". It is a part of Alite-Deconflictiontools project. Brief instructions on how to build it and use it are here:  
http://jones.felk.cvut.cz/redmine/projects/deconflictiontools/wiki

**Comment by ghost** [comment]
Thank you!

**Comment by ghost** [comment]
Is it possible to generate an initial problem instance (i.e. world with obstacles) from an image file? For example, ubremen seems like a 2D occupancy map

**Comment by mcapino** [comment]
The environments are indeed occupancy maps converted to polygonal representation. I did that using a simple tool (python + opencv) that was developed by a collaborator of mine. Unfortunately, since I did not write the tool, it is not released open source within this repository.

**Comment by ghost** [comment]
I understand. Thank you
